# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages: 
 - stage: Build
   jobs:
   - job: FirstJob
     steps: 
      - bash: echo Build FirstJob
      - bash: echo $(PipelineLevelVariable)
      - bash: echo $(Build.BuildNumber)
      - bash: echo $(Build.BuildId)
      - bash: echo $(Build.SourceBranchName)
      - bash: echo $(Build.SourcesDirectory)
      - bash: echo $(Build.DefaultWorkingDirectory)
      - bash: ls -R $(System.DefaultWorkingDirectory)
      - bash: echo $(Build.ArtifactStagingDirectory)
      - bash: java -version
      - bash: node --version
      - bash: python --version
      - bash: mvn -version
      - bash: ls -R echo $(Build.ArtifactStagingDirectory)
      - task: CopyFiles@2
        inputs:
          SourceFolder: '$(System.DefaultWorkingDirectory)'
          Contents: |
            **/*.yaml
            **/*.tf
          TargetFolder: '$(Build.ArtifactStagingDirectory)'
      - bash: ls -R echo $(Build.ArtifactStagingDirectory)
        

  #  - job: secondjob
  #    steps:
  #     - bash: echo build secondjob
#  - stage: DevDeploy
#    variables:
#      environment: Dev 
#    dependsOn: Build
#    jobs:
#    - job: devdeployJob
#      steps:
#       - bash: echo $(environment)Deploy
#  - stage: QaDeploy
#    variables:
#      environment: Qa
#    dependsOn: Build
#    jobs:
#    - job: qadeployjob
#      steps:
#       - bash: echo $(environment)Deploy
#  - stage: ProdDeploy
#    dependsOn:
#    - DevDeploy
#    - QaDeploy

#    jobs:
#    - job: prodedeployjob
#      steps: 
#       - bash: echo proddeploy
